/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'sso-casbin': RouteRecordInfo<'sso-casbin', '/sso/casbin', Record<never, never>, Record<never, never>>,
    'sso-permissions': RouteRecordInfo<'sso-permissions', '/sso/permissions', Record<never, never>, Record<never, never>>,
    'sso-roles': RouteRecordInfo<'sso-roles', '/sso/roles', Record<never, never>, Record<never, never>>,
    'sso-tenants': RouteRecordInfo<'sso-tenants', '/sso/tenants', Record<never, never>, Record<never, never>>,
    'sso-users': RouteRecordInfo<'sso-users', '/sso/users', Record<never, never>, Record<never, never>>,
  }
}
