/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'agents': RouteRecordInfo<'agents', '/agents', Record<never, never>, Record<never, never>>,
    'agents-skills': RouteRecordInfo<'agents-skills', '/agents/skills', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'events': RouteRecordInfo<'events', '/events', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'project-management': RouteRecordInfo<'project-management', '/project-management', Record<never, never>, Record<never, never>>,
    'project-management-id-tasks': RouteRecordInfo<'project-management-id-tasks', '/project-management/:id/tasks', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'sdlc': RouteRecordInfo<'sdlc', '/sdlc', Record<never, never>, Record<never, never>>,
    'settings-credentials': RouteRecordInfo<'settings-credentials', '/settings/credentials', Record<never, never>, Record<never, never>>,
    'settings-github': RouteRecordInfo<'settings-github', '/settings/github', Record<never, never>, Record<never, never>>,
    'settings-jira': RouteRecordInfo<'settings-jira', '/settings/jira', Record<never, never>, Record<never, never>>,
    'settings-models': RouteRecordInfo<'settings-models', '/settings/models', Record<never, never>, Record<never, never>>,
    'sso-permissions': RouteRecordInfo<'sso-permissions', '/sso/permissions', Record<never, never>, Record<never, never>>,
    'sso-roles': RouteRecordInfo<'sso-roles', '/sso/roles', Record<never, never>, Record<never, never>>,
    'sso-tenants': RouteRecordInfo<'sso-tenants', '/sso/tenants', Record<never, never>, Record<never, never>>,
    'sso-users': RouteRecordInfo<'sso-users', '/sso/users', Record<never, never>, Record<never, never>>,
    'workflow-definitions': RouteRecordInfo<'workflow-definitions', '/workflow/definitions', Record<never, never>, Record<never, never>>,
    'workflow-definitions-builder': RouteRecordInfo<'workflow-definitions-builder', '/workflow/definitions/builder', Record<never, never>, Record<never, never>>,
    'workflow-executions': RouteRecordInfo<'workflow-executions', '/workflow/executions', Record<never, never>, Record<never, never>>,
  }
}
