[package]
name = "sdlc-container"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sdlc-container"
path = "src/main.rs"

[dependencies]
sdlc-application = { path = "../sdlc-application" }
sdlc-dataaccess = { path = "../sdlc-dataaccess" }
sdlc-domain = { path = "../sdlc-domain" }
migration = { path = "../migration" }

tokio = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
dotenvy = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tower-http = { workspace = true }
uuid = { workspace = true }
